#config_version=5

show_player:
  mode_attract_started: attract_display_loop
  mode_attract_started.1: rainbow
 

shows:
  rainbow:
    - lights:
        L1: 0
        L2: ff
    - lights:
        L1: ff
        L2: 0

