#config_version=5

#
mpf:
    report_crashes: "never"

hardware:
    platform: opp
    driverboards: gen2

opp:
    ports: COM10, COM11



lights:
  some_led:
    number: 0-0-1
    subtype: led
    type: rgb


window:
    title: MPF OPP Test
    width: 640
    height: 480
