#config_version=5

#
mpf:
    report_crashes: "never"

hardware:
    platform: opp
    driverboards: gen2

opp:
    ports: COM7


switches:
    # Wing 0 is Neopixel, 1 is input, 2 is input, 3 is input
    

lights:
  some_led:
    number: 0-1
    subtype: led
    type: rgb


window:
    title: MPF OPP Test
    width: 640
    height: 480
