#config_version=5
mode:
    start_events: ball_starting
    priority: 100
    
slide_player:
  mode_base_started: mode_base_started_slide
        
        
variable_player:
    s_left_sling_active:
        score: 100
    s_right_sling_active:
        score: 100
    s_popbumber_1_active:
        score: 100
    s_popbumber_2_active:
        score: 100
    s_popbumber_3_active:        
        score: 100    

        
    s_bottomlane1_active:
        score: 1000
    s_bottomlane2_active:
        score: 1000
    s_bottomlane3_active:
        score: 1000
    s_bottomlane4_active:
        score: 1000



    
        