#config_version=5

# displays:
#   window:
#     width: 800
#     height: 600


window:
  width: 1400
  height: 800
  title: portal pinball
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true


displays:
  window:
    width: 1400  
    height: 800  

  Disp_Player:
    width: 450
    height: 150
  Disp_Menu:
    width: 300
    height: 200
  Disp_Ball:
    width: 450
    height: 150
  Disp_Message:
    width: 600
    height: 200
  Disp_Counter:
    width: 300
    height: 100
  Disp_Score:
    width: 600
    height: 200
  Disp_Icons:
    width: 300
    height: 350
  
        
