#config_version=5

# displays:
#   window:
#     width: 800
#     height: 600


window:
  width: 1000
  height: 800
  title: portal pinball
  resizable: true
  fullscreen: false
  borderless: false
  exit_on_escape: true

slide_player:
  init_done: welcome_slide              
