#config_version=5


virtual_platform_start_active_switches:
  - s_trough1
  - s_trough2
  - s_trough3
  - s_trough4



keyboard:
  1:
    switch: s_trough1
    toggle: true
  2:
    switch: s_trough2
    toggle: true
  3:
    switch: s_trough3
    toggle: true
  4:
    switch: s_trough4
    toggle: true
  5:
    switch: s_trough5
    toggle: true
  6:
    switch: s_trough_jam
    toggle: true



  0:
    switch: s_start
  9:
    switch: s_plunger_lane
    toggle: true

    
  m:
    switch: s_right_sling 
  x:
    switch: s_left_sling

  q: 
    switch: s_vukmid 
  w: 
    switch: s_drop1 
    toggle: true
  e: 
    switch: s_drop2 
    toggle: true
  r: 
    switch: s_drop3 
    toggle: true

  t: 
    switch: s_bottomlane1 
  y: 
    switch: s_bottomlane2 
  u: 
    switch: s_bottomlane3 
  i: 
    switch: s_bottomlane4 
  o: 
    switch: s_bottomlane5 

  a:
    switch: s_toplane1
  s:
    switch: s_toplane2
  d:
    switch: s_toplane3


    
    

    