#config_version=5
shows:
  rainbow:
    - lights:
        (leds): red #-f1s
    - lights:
        (leds): orange
    - lights:
        (leds): yellow
    - lights:
        (leds): green
    - lights:
        (leds): blue
    - lights:
        (leds): purple